sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es1b
sonar.projectName=yovi_es1b

# Mantenemos las fuentes
sonar.sources=webapp/src,users,gamey/src
sonar.tests=webapp/src/__tests__,users/__tests__,gamey/tests
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.spec.ts,**/*.spec.tsx,**/*.spec.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,webapp/src/__tests__/**,users/__tests__/**,gamey/target/**
sonar.coverage.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.spec.ts,**/*.spec.tsx,**/*.spec.js,**/*.d.ts
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info